n = input('digite algo:')
tipo = (type(n))
num = (n.isnumeric())
anum = (n.isalnum())
alpha = (n.isalpha())
maiusculo = (n.isupper())
minusculo = (n.islower())
capitalizado = (n.istitle())
print('O tipo de da variavel digitada é {}'.format(tipo))
print('a variavel digitada é um numero? {}'.format(num))
print('a variavel digitada é um alfanumerico? {}'.format(anum))
print('a variavel digitada é do alfabeto? {}'.format(alpha))
print('a variavel é maiusculo? {}' .format(maiusculo))
print('a variavel é minusculo? {}' .format(minusculo))
print('a variavel está capitalizada? {}' .format(capitalizado))

